"""GitHub authenticator helper: encrypt a TOTP secret and copy live codes."""

import base64
import binascii
import hashlib
import hmac
import importlib
import os
import struct
import subprocess
import sys
import time
import urllib.parse
from pathlib import Path

# Keep portable installs free of generated bytecode caches.
sys.dont_write_bytecode = True

try:
    import tkinter as tk
    from tkinter import messagebox, simpledialog, ttk
except ImportError:
    # Keep the crypto and TOTP helpers importable in headless Python builds.
    tk = None
    messagebox = None
    simpledialog = None
    ttk = None

# Optional convenience for a personal copy of this script. Leave blank to be
# prompted for the password. Anyone who can read this file can read this value.
HARDCODED_PASSWORD = ""

APP_DIR = Path(__file__).resolve().parent
SECRET_FILE = APP_DIR / "secret.bin"
LIBS_DIR = APP_DIR / "libs"
FILE_MAGIC = b"G2FA\x01"
TOTP_PERIOD = 30
TOTP_DIGITS = 6


def normalize_secret(secret):
    """Return a validated, uppercase Base32 secret without visual separators."""
    secret = secret.strip()

    # Accept an authenticator URI as a convenience, as well as a raw secret.
    if secret.lower().startswith("otpauth://"):
        query = urllib.parse.parse_qs(urllib.parse.urlparse(secret).query)
        values = query.get("secret", [])
        if not values:
            raise ValueError("The authenticator URI does not contain a secret.")
        secret = values[0]

    normalized = "".join(
        character for character in secret.upper()
        if not character.isspace() and character not in "-"
    )
    normalized = normalized.rstrip("=")

    if not normalized:
        raise ValueError("Paste the Base32 authenticator secret from GitHub.")

    allowed_characters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567"
    if any(character not in allowed_characters for character in normalized):
        raise ValueError(
            "The secret must use Base32 characters: A-Z and digits 2-7."
        )

    try:
        decoded = base64.b32decode(
            normalized + "=" * ((-len(normalized)) % 8),
            casefold=True
        )
    except (ValueError, binascii.Error) as error:
        raise ValueError("That is not a valid Base32 secret.") from error

    if len(decoded) < 10:
        raise ValueError("The authenticator secret is too short to be valid.")

    return normalized


def generate_totp(secret, timestamp=None, digits=TOTP_DIGITS, period=TOTP_PERIOD):
    """Generate a standard six-digit, 30-second TOTP code."""
    normalized = normalize_secret(secret)
    key = base64.b32decode(
        normalized + "=" * ((-len(normalized)) % 8),
        casefold=True
    )
    now = time.time() if timestamp is None else timestamp
    counter = int(now // period)
    digest = hmac.new(key, struct.pack(">Q", counter), hashlib.sha1).digest()
    offset = digest[-1] & 0x0F
    binary_code = int.from_bytes(digest[offset:offset + 4], "big") & 0x7FFFFFFF
    return f"{binary_code % (10 ** digits):0{digits}d}"


def _fernet_classes():
    """Load Fernet, installing cryptography into the portable libs folder if needed."""
    if str(LIBS_DIR) not in sys.path:
        sys.path.insert(0, str(LIBS_DIR))

    try:
        from cryptography.fernet import Fernet, InvalidToken
        return Fernet, InvalidToken
    except ImportError:
        result = subprocess.run(
            [
                sys.executable,
                "-m",
                "pip",
                "install",
                "--upgrade",
                "--no-compile",
                "--target",
                str(LIBS_DIR),
                "cryptography",
            ],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding="utf-8",
            errors="replace",
        )

        if result.returncode != 0:
            detail = result.stdout.strip()[-2000:]
            raise RuntimeError(
                "Could not install cryptography. Check your internet "
                "connection, or install it with:\n"
                f"{sys.executable} -m pip install cryptography\n\n{detail}"
            )

        importlib.invalidate_caches()
        from cryptography.fernet import Fernet, InvalidToken
        return Fernet, InvalidToken


class SecretPasswordError(ValueError):
    """Raised when a password cannot authenticate a secret.bin payload."""


def _derive_fernet_key(password, salt):
    key = hashlib.scrypt(
        password.encode("utf-8"),
        salt=salt,
        n=2 ** 14,
        r=8,
        p=1,
        dklen=32,
    )
    return base64.urlsafe_b64encode(key)


def encrypt_secret(secret, password):
    """Encrypt a Base32 secret using scrypt and Fernet."""
    if not password:
        raise ValueError("A password is required to encrypt the secret.")

    normalized = normalize_secret(secret)
    Fernet, _ = _fernet_classes()
    salt = os.urandom(16)
    ciphertext = Fernet(_derive_fernet_key(password, salt)).encrypt(
        normalized.encode("ascii")
    )
    return FILE_MAGIC + salt + ciphertext


def decrypt_secret(encrypted_data, password):
    """Decrypt and validate a secret.bin payload."""
    if not password:
        raise ValueError("A password is required to decrypt the secret.")

    if not encrypted_data.startswith(FILE_MAGIC):
        raise ValueError("secret.bin has an unknown or damaged file format.")

    offset = len(FILE_MAGIC)
    if len(encrypted_data) <= offset + 16:
        raise ValueError("secret.bin is incomplete or damaged.")

    salt = encrypted_data[offset:offset + 16]
    ciphertext = encrypted_data[offset + 16:]
    Fernet, InvalidToken = _fernet_classes()
    try:
        plaintext = Fernet(_derive_fernet_key(password, salt)).decrypt(ciphertext)
    except InvalidToken as error:
        raise SecretPasswordError(
            "Incorrect password or damaged secret.bin."
        ) from error

    return normalize_secret(plaintext.decode("ascii"))


def save_secret_file(secret, password):
    """Write an encrypted secret atomically and restrict file permissions."""
    payload = encrypt_secret(secret, password)
    temporary_file = SECRET_FILE.with_name(SECRET_FILE.name + ".tmp")

    try:
        temporary_file.write_bytes(payload)
        try:
            os.chmod(temporary_file, 0o600)
        except OSError:
            # Windows filesystems may not support POSIX permission bits.
            pass
        os.replace(temporary_file, SECRET_FILE)
    finally:
        try:
            temporary_file.unlink()
        except FileNotFoundError:
            pass


class TwoFAHelper:
    def __init__(self, root):
        self.root = root
        self.secret = None
        self.code_var = tk.StringVar(value="------")
        self.expiry_var = tk.StringVar(value="Unlock or save a secret to begin.")
        self.status_var = tk.StringVar(value="No secret loaded.")

        root.title("GitHub 2FA Helper")
        root.geometry("520x390")
        root.minsize(460, 350)

        self._build_interface()
        self.root.after(100, self.unlock_saved_secret)
        self.root.after(500, self.refresh_code)

    def _build_interface(self):
        frame = ttk.Frame(self.root, padding=20)
        frame.pack(fill=tk.BOTH, expand=True)

        ttk.Label(
            frame,
            text="GitHub 2FA Helper",
            font=("Arial", 20, "bold"),
        ).pack(pady=(0, 5))

        ttk.Label(
            frame,
            text=(
                "Paste the Base32 authenticator secret from GitHub. "
                "It is usually 32 characters."
            ),
            wraplength=460,
            justify=tk.CENTER,
        ).pack(pady=(0, 14))

        self.secret_entry = ttk.Entry(frame)
        self.secret_entry.pack(fill=tk.X, pady=(0, 9))

        buttons = ttk.Frame(frame)
        buttons.pack(fill=tk.X)

        ttk.Button(
            buttons,
            text="Encrypt & Save Secret",
            command=self.save_secret,
        ).pack(side=tk.LEFT, expand=True, fill=tk.X, padx=(0, 4))

        self.unlock_button = ttk.Button(
            buttons,
            text="Unlock saved secret",
            command=self.unlock_saved_secret,
        )
        self.unlock_button.pack(side=tk.LEFT, expand=True, fill=tk.X, padx=(4, 0))

        ttk.Separator(frame).pack(fill=tk.X, pady=20)

        ttk.Label(frame, text="Current one-time pass key:").pack()

        tk.Label(
            frame,
            textvariable=self.code_var,
            font=("Consolas", 38, "bold"),
            fg="#6c5ce7",
        ).pack(pady=(5, 0))

        ttk.Label(frame, textvariable=self.expiry_var).pack(pady=(0, 12))

        self.copy_button = ttk.Button(
            frame,
            text="Copy pass key",
            command=self.copy_code,
            state=tk.DISABLED,
        )
        self.copy_button.pack()

        ttk.Label(
            frame,
            textvariable=self.status_var,
            wraplength=460,
            justify=tk.CENTER,
        ).pack(pady=(15, 0))

    def _new_password(self):
        if HARDCODED_PASSWORD:
            return HARDCODED_PASSWORD

        password = simpledialog.askstring(
            "Encrypt secret",
            "Create a password (at least 8 characters):",
            show="*",
            parent=self.root,
        )
        if password is None:
            return None

        if len(password) < 8:
            messagebox.showwarning(
                "Password too short",
                "Use at least 8 characters for the encryption password.",
                parent=self.root,
            )
            return None

        confirmation = simpledialog.askstring(
            "Confirm password",
            "Enter the password again:",
            show="*",
            parent=self.root,
        )
        if confirmation is None:
            return None

        if password != confirmation:
            messagebox.showerror(
                "Password mismatch",
                "The passwords do not match.",
                parent=self.root,
            )
            return None

        return password

    def _ask_unlock_password(self):
        return simpledialog.askstring(
            "Unlock secret.bin",
            "Enter the password for secret.bin:",
            show="*",
            parent=self.root,
        )

    def save_secret(self):
        try:
            secret = normalize_secret(self.secret_entry.get())
        except ValueError as error:
            messagebox.showerror(
                "Invalid authenticator secret",
                str(error),
                parent=self.root,
            )
            return

        if SECRET_FILE.exists() and not messagebox.askyesno(
            "Replace saved secret?",
            "secret.bin already exists. Replace it with this secret?",
            parent=self.root,
        ):
            return

        password = self._new_password()
        if password is None:
            return

        try:
            save_secret_file(secret, password)
        except Exception as error:
            messagebox.showerror(
                "Could not save secret",
                str(error),
                parent=self.root,
            )
            return

        self.secret = secret
        self.secret_entry.delete(0, tk.END)
        self.status_var.set(f"Encrypted secret saved as {SECRET_FILE.name}.")
        self.copy_button.configure(state=tk.NORMAL)
        self.refresh_code(schedule=False)

    def unlock_saved_secret(self):
        if self.secret is not None:
            self.status_var.set("The saved secret is already unlocked.")
            return

        if not SECRET_FILE.is_file():
            self.status_var.set("Paste a secret above, then encrypt and save it.")
            return

        try:
            encrypted_data = SECRET_FILE.read_bytes()
        except OSError as error:
            messagebox.showerror(
                "Could not read secret.bin",
                str(error),
                parent=self.root,
            )
            return

        password = HARDCODED_PASSWORD or self._ask_unlock_password()
        if password is None:
            self.status_var.set(
                "Unlock cancelled. The encrypted secret is unchanged."
            )
            return

        try:
            secret = decrypt_secret(encrypted_data, password)
        except SecretPasswordError as first_error:
            # A configured constant is only a convenience; allow a manual
            # password if it is stale or incorrect.
            if HARDCODED_PASSWORD:
                password = self._ask_unlock_password()
                if password is None:
                    self.status_var.set(
                        "Unlock cancelled. The encrypted secret is unchanged."
                    )
                    return
                try:
                    secret = decrypt_secret(encrypted_data, password)
                except Exception as error:
                    messagebox.showerror(
                        "Unlock failed",
                        f"Incorrect password or damaged secret.bin.\n\n{error}",
                        parent=self.root,
                    )
                    return
            else:
                messagebox.showerror(
                    "Unlock failed",
                    str(first_error),
                    parent=self.root,
                )
                return
        except Exception as error:
            messagebox.showerror(
                "Unlock failed",
                str(error),
                parent=self.root,
            )
            return

        self.secret = secret
        self.status_var.set(f"Unlocked {SECRET_FILE.name} for this session.")
        self.copy_button.configure(state=tk.NORMAL)
        self.refresh_code(schedule=False)

    def refresh_code(self, schedule=True):
        if self.secret is not None:
            now = time.time()
            self.code_var.set(generate_totp(self.secret, timestamp=now))
            remaining = TOTP_PERIOD - (int(now) % TOTP_PERIOD)
            self.expiry_var.set(f"Code refreshes in {remaining} seconds.")
            self.copy_button.configure(state=tk.NORMAL)
        else:
            self.code_var.set("------")
            self.expiry_var.set("Unlock or save a secret to begin.")
            self.copy_button.configure(state=tk.DISABLED)

        if schedule:
            self.root.after(1000, self.refresh_code)

    def copy_code(self):
        if self.secret is None:
            return

        code = generate_totp(self.secret)
        self.root.clipboard_clear()
        self.root.clipboard_append(code)
        self.root.update_idletasks()
        self.code_var.set(code)
        self.status_var.set("Current pass key copied to the clipboard.")


def main():
    if tk is None:
        raise SystemExit("Tkinter is required to run the 2FA helper GUI.")

    root = tk.Tk()
    TwoFAHelper(root)
    root.mainloop()


if __name__ == "__main__":
    main()
